# This file is part of DynExp.

target_sources(DynExpModules PRIVATE "ArbitraryFunctionFromCSV.cpp" "ArbitraryFunctionFromCSV.h")
target_sources(DynExpModules PRIVATE "EventSender.cpp" "EventSender.h" "EventSender.ui")
target_sources(DynExpModules PRIVATE "gRPCModule.cpp" "gRPCModule.h")
target_sources(DynExpModules PRIVATE "InputPortReader.cpp" "InputPortReader.h" "InputPortReader.ui")
target_sources(DynExpModules PRIVATE "LaserControl.cpp" "LaserControl.h" "LaserControl.ui")
target_sources(DynExpModules PRIVATE "LockinAmplifierControl.cpp" "LockinAmplifierControl.h" "LockinAmplifierControl.ui")
target_sources(DynExpModules PRIVATE "NetworkAnalogInModule.cpp" "NetworkAnalogInModule.h")
target_sources(DynExpModules PRIVATE "NetworkAnalogOutModule.cpp" "NetworkAnalogOutModule.h")
target_sources(DynExpModules PRIVATE "NetworkDataStreamInstrumentModule.cpp" "NetworkDataStreamInstrumentModule.h")
target_sources(DynExpModules PRIVATE "NetworkDigitalInModule.cpp" "NetworkDigitalInModule.h")
target_sources(DynExpModules PRIVATE "NetworkDigitalOutModule.cpp" "NetworkDigitalOutModule.h")
target_sources(DynExpModules PRIVATE "NetworkTimeTaggerModule.cpp" "NetworkTimeTaggerModule.h")
target_sources(DynExpModules PRIVATE "OutputPortWriter.cpp" "OutputPortWriter.h" "OutputPortWriter.ui")
target_sources(DynExpModules PRIVATE "SignalDesigner.cpp" "SignalDesigner.h" "InputPortReader.ui")
target_sources(DynExpModules PRIVATE "SignalPlotter.cpp" "SignalPlotter.h" "SignalPlotter.ui")
target_sources(DynExpModules PRIVATE "Stage1D.cpp" "Stage1D.h" "Stage1D.ui")
target_sources(DynExpModules PRIVATE "StreamManipulator.cpp" "StreamManipulator.h")
target_sources(DynExpModules PRIVATE "Trajectory1D.cpp" "Trajectory1D.h" "Trajectory1D.ui")

add_subdirectory(ImageViewer)
add_subdirectory(LaserScanningSpectroscopy)
add_subdirectory(ODMR)
add_subdirectory(SpectrumViewer)
add_subdirectory(WidefieldMicroscope)